# access conf

ver = "1.0.0"
logPath = "/tmp/access.log"

[server]
proto = "tcp"
addr = "127.0.0.1:11000"

[rpcServer]
proto = "tcp"
addr = "127.0.0.1:20000"

[serviceDiscoveryServer]
serviceName = "access"
rpcAddr = "127.0.0.1:20000"
etcdAddr = "localhost:2379"
interval = "5s"
ttl = "10s"

[rpcClient]
    [rpcClient.logicClient]
    serviceName = "logic"
    etcdAddr = "localhost:2379"
    balancer = "rr"

[confDiscovery]
    [confDiscovery.gateway]
    name = "access_server_11000"
    root = "/server/access_server_gateway/"
    addrs = ["localhost:2379"]
    timeout = "1s"
    [confDiscovery.msgJob]
    name = "access_server_20000"
    root = "/server/access_server_msgjob/"
    addrs = ["localhost:2379"]
    timeout = "1s"
    [confDiscovery.notify]
    name = "access_server_20000"
    root = "/server/access_server_notify/"
    addrs = ["localhost:2379"]
    timeout = "1s"
    [confDiscovery.logic]
    name = "access_server_20000"
    root = "/server/access_server_logic/"
    addrs = ["localhost:2379"]
    timeout = "1s"

