# gateway conf

ver = "1.0.0"
logPath = "/tmp/gateway.log"

[server]
proto = "tcp"
addr = "0.0.0.0:10000"

[confDiscovery]
role = "master"
interval = "10s"

[etcd]
root = "/server/access_server_gateway/"
addrs = ["127.0.0.1:2379"]
timeout = "1s"

